import type { Metadata } from "next"
import localFont from "next/font/local"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Navbar } from "@/components/partials/navbar"
import { Footer } from "@/components/partials/footer"

// Local font (Samim)
const myFont = localFont({
  src: [
    {
      path: '../public/Samim-Medium.ttf',
      style: 'normal',
    },

  ],
  variable: '--font-myfont', // Optional: Use a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa" dir="rtl" >
      <body
       className={`${myFont.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
